#pragma checksum "..\..\..\..\..\Views\ReaderWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0DD41A488E79B68B98A4A8BE83B514042321DA49"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using FloatingNovelReader.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FloatingNovelReader.Views {
    
    
    /// <summary>
    /// ReaderWindow
    /// </summary>
    public partial class ReaderWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 21 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FloatingNovelReader.Views.ReaderWindow Root;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RootBorder;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RootGrid;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border TextArea;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer TextScroll;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PageTextView;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid TopHitArea;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FloatingNovelReader.Controls.OverlayControlBar TopBar;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid BottomHitArea;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal FloatingNovelReader.Controls.OverlayControlBar BottomBar;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\..\Views\ReaderWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusTextView;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.28.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FloatingNovelReader;V1.0.0.0;component/views/readerwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\ReaderWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.28.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.28.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((FloatingNovelReader.Views.ReaderWindow)(target));
            
            #line 17 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.Root.Loaded += new System.Windows.RoutedEventHandler(this.OnLoaded);
            
            #line default
            #line hidden
            
            #line 18 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.Root.Closing += new System.ComponentModel.CancelEventHandler(this.OnClosing);
            
            #line default
            #line hidden
            
            #line 19 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.Root.SizeChanged += new System.Windows.SizeChangedEventHandler(this.OnSizeChanged);
            
            #line default
            #line hidden
            
            #line 20 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.Root.LocationChanged += new System.EventHandler(this.OnLocationChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.RootBorder = ((System.Windows.Controls.Border)(target));
            
            #line 34 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.RootBorder.MouseLeftButtonDown += new System.Windows.Input.MouseButtonEventHandler(this.OnBorderMouseLeftButtonDown);
            
            #line default
            #line hidden
            return;
            case 3:
            this.RootGrid = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.TextArea = ((System.Windows.Controls.Border)(target));
            return;
            case 5:
            this.TextScroll = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 6:
            this.PageTextView = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.TopHitArea = ((System.Windows.Controls.Grid)(target));
            
            #line 55 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.TopHitArea.MouseEnter += new System.Windows.Input.MouseEventHandler(this.OnTopAreaEnter);
            
            #line default
            #line hidden
            
            #line 55 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.TopHitArea.MouseLeave += new System.Windows.Input.MouseEventHandler(this.OnTopAreaLeave);
            
            #line default
            #line hidden
            return;
            case 8:
            this.TopBar = ((FloatingNovelReader.Controls.OverlayControlBar)(target));
            return;
            case 9:
            this.BottomHitArea = ((System.Windows.Controls.Grid)(target));
            
            #line 65 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.BottomHitArea.MouseEnter += new System.Windows.Input.MouseEventHandler(this.OnBottomAreaEnter);
            
            #line default
            #line hidden
            
            #line 65 "..\..\..\..\..\Views\ReaderWindow.xaml"
            this.BottomHitArea.MouseLeave += new System.Windows.Input.MouseEventHandler(this.OnBottomAreaLeave);
            
            #line default
            #line hidden
            return;
            case 10:
            this.BottomBar = ((FloatingNovelReader.Controls.OverlayControlBar)(target));
            return;
            case 11:
            this.StatusTextView = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

