#pragma checksum "..\..\..\..\..\Controls\OverlayControlBar.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4CA13D08509DBF097055324BDD66B811F495B656"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace FloatingNovelReader.Controls {
    
    
    /// <summary>
    /// OverlayControlBar
    /// </summary>
    public partial class OverlayControlBar : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 12 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button MenuBtn;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BookTitleText;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ChapterText;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SettingsBtn;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CloseBtn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.28.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/FloatingNovelReader;V1.0.0.0;component/controls/overlaycontrolbar.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.28.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.MenuBtn = ((System.Windows.Controls.Button)(target));
            
            #line 15 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
            this.MenuBtn.Click += new System.Windows.RoutedEventHandler(this.OnMenuClick);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 35 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnMenuChapterList);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 36 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnMenuBookmarkList);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 38 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
            ((System.Windows.Controls.MenuItem)(target)).Click += new System.Windows.RoutedEventHandler(this.OnMenuSettings);
            
            #line default
            #line hidden
            return;
            case 5:
            this.BookTitleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.ChapterText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.SettingsBtn = ((System.Windows.Controls.Button)(target));
            
            #line 52 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
            this.SettingsBtn.Click += new System.Windows.RoutedEventHandler(this.OnSettingsClick);
            
            #line default
            #line hidden
            return;
            case 8:
            this.CloseBtn = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\..\Controls\OverlayControlBar.xaml"
            this.CloseBtn.Click += new System.Windows.RoutedEventHandler(this.OnCloseClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

